{{ define "com.flipkart.hbaseoperator.rolebindings" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:{{ .Values.roleBindings.operatorRoleBindingName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ default "Role" .Values.roles.operatorRoleKind }}
  name: {{ .Values.roles.operatorRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.operatorServiceAccount }}
  namespace: {{ .Values.operatorNamespace }}
{{ end }}

---

{{ define "com.flipkart.hbasecluster.rolebindings" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindings.fencingRoleBindingName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ default "Role" .Values.roles.fencingRoleKind }}
  name: {{ .Values.roles.fencingRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.fencingServiceAccount }}
    namespace: {{ .Values.namespace }}
{{ end }}