{{- define "com.flipkart.hbaseresources.serviceaccounts" }}
{{- if .Values.additionalServiceAccounts }}
{{- range .Values.additionalServiceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ default $.Values.namespace .namespace }}
{{- end }}
{{- end }}
{{- end }}