{{- define "com.flipkart.hbasecluster.serviceaccounts" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.additionalServiceAccounts.fencingServiceAccount }}
  namespace: {{ .Values.namespace }}
{{- end }}