{{- define "com.flipkart.hbaseresources.serviceaccounts" }}
{{- range .Values.additionalServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.namespace }}
{{- end }}
{{- end }}}