name: operator-hbase
namespace: hbase-operator-ns
replicaCount: 1
serviceAccountName: hbase-operator-controller-manager
managerRoleName: hbase-operator-manager-role
managerRoleBindingName: hbase-operator-manager-rolebinding
leaderElectionRoleName: hbase-operator-leader-election-role
namespaces:
  - hbase-standalone-ns
  - hbase-cluster-ns
  - hbase-tenant-ns
image:
  hbase_operator:
    image_name: hbase-operator
    tag: v1.0.0
  kube_rbac_proxy:
    image_name: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
