sonar.projectKey=hbase-operator
sonar.projectName=hbase-operator

sonar.sources=.
sonar.exclusions=**/*_test.go,**/cmd/**,**/vendor/**,**/mocks/**,**/dal/**,**/deployment/**,**/constants/**, **/go.mod, **/go.sum,**/authz_access.json, 
**/README.md
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out